(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph
open Money_sharing

type path = string

(* Values are read as strings. *)
val from_file: path -> string graph

(* Similarly, we write only a string graph.
 * If necessary, use gmap (to be written by you) to prepare the input graph. *)
val write_file: path -> string graph -> unit


(* The format of files is compatible with the files generated by:
   https://algorithms.discrete.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)

(* Writes a string graph in dot format *)
val export : path -> string graph -> unit

(* Students-made functions *)
val l_persons_from_file : path -> person list

val export_MS : path -> string graph -> person list ->  unit